### ISSUE TITLE
The crawler should store meta data

### ISSUE THREAD

**Issue by earthquakesan** [dice-group/Squirrel#10]
The system should offer a central storage containing the metadata that has been collected during the crawling. This meta data might contain (but is not limited to):

timestamp at which the crawling has been finished
status of the crawling (maybe we need the information whether the crawling was successful?)
dcat like information, e.g., that a crawled dump contains the same information as a certain SPARQL endpoint (that does not have to be crawled anymore)
name of the dump file that has been created
please add additional meta data if needed...

Micha:
Following "eat your own dog food" it would be the best solution. However, I would like to implement the frontier in a way that it can work directly on this store, e.i., throws a lot of queries against it to make sure whether a given URI has not been crawled before. Thus, it has to be

fast
able to perform read and write queries at the same time (not exactly at the same time, but you know what I mean ;-) )

**Comment by earthquakesan** [comment]
Metadata should include GRAPH information from SPARQL endpoint (if crawled from SPARQL endpoint)

**Comment by MichaelRoeder** [comment]
## Overview
The meta data will be collected in the worker while crawling. There will be a meta data graph for every attempt a worker is doing to crawl a URI. Even if a URI is crawled multiple times, the single crawling activities need to have different URIs. Therefore, the worker will create a UUID-based URI for every crawleable URI. This URI will be used (with different suffixes) for
* the activity resource in the meta data
* the name of the graph (or file) containing the crawled data
* the plan resource in the meta data comprising information about the single activities of the crawler

## Meta data model

The meta data should be available as RDF with the following structure (the description below will contain several enhancements):
![screenshot from 2018-08-21 11-49-56](https://user-images.githubusercontent.com/6122307/44394904-a7658500-a538-11e8-9de3-a2892d84d04d.png)

Regarding prefixes, we assume that `prov` is the PROV-O ontology, `sq` stands for the Squirrel vocabulary while `meta` is the prefix of all generated instance URIs (e.g., the acitivity URI). We assume that the UUID used for our example is `123`.

```turtle
@prefix rdfs:     <http://www.w3.org/2000/01/rdf-schema#> .
@prefix xsd:      <http://www.w3.org/2001/XMLSchema#> .
@prefix prov:     <http://www.w3.org/ns/prov-o/> .
@prefix sq:       <http://www.w3id.org/squirrel/vocab#> .
@prefix meta:     <http://www.w3id.org/squirrel/metadata#> .

meta:123_activity a prov:Activity;
        prov:qualifiedAssociation meta:123_workerAssociation;
        prov:wasAssociatedWith meta:Worker_ID;
        prov:startedAtTime "2018-05-01T00:00:00Z"^^xsd:dateTime;
        prov:endedAtTime   "2018-05-01T01:11:00Z"^^xsd:dateTime;
        sq:crawledUri <http://example.org/myExample>;
        sq:numberOfTriples "99"^^xsd:long;
        sq:hostedOn "8.8.8.8";
        sq:status "successfull" .

meta:123_workerAssociation a prov:Association;
        prov:agent   meta:Worker_ID;
	prov:hadPlan meta:123_Plan .

meta:123_plan a prov:Plan;
	rdfs:comment """org.dice_research.squirrel.fetcher.HTTPFetcher,
org.dice_research.squirrel.analyzer.impl.RDFAnalyzer,
...""" .

meta:123_resultgraph a prov:Entity;
	prov:wasGeneratedBy meta:123_activity;
	sq:containsDataOf <http://example.org/myExample> .

meta:Worker_ID a  prov:Agent .

```
`meta:Worker_ID` is a unique URI of a worker. `http://example.org/myExample` is the URI that has been crawled.

## Implementation details
- [ ] There should be a class which is used for storing this data (either as RDF or as java object which is later transformed into RDF.
- [ ] When starting to crawl a URI, the worker should create the following objects and add them to the [data map](https://github.com/dice-group/Squirrel/blob/master/src/main/java/org/aksw/simba/squirrel/data/uri/CrawleableUri.java#L118) of the crawleable URI
    - [ ] Create a UUID and the necessary URIs for the crawling activity, etc.
    - [ ] Create the meta data object for the crawlable URI
    - [ ] Set the starting time
- [ ] During the crawling process, every class that is handling the URI and influences the result or the data of the URI, should add itself to a list of strings (easiest case: add the name of the class).
- [ ] When opening the sink for the URI, the sink should get the result graph URI and use that for creating a graph (or a file) instead of using the crawleable URI directly.
- [ ] When closing the sink for the URI, the sink should add the number of triples it saw for this URI.
- [ ] When the worker is done with the crawling, it should add the end timestamp and write the meta data to the meta data graph using the method of its sink.
